// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practical_18.Models.Data;

#nullable disable

namespace Practical_18.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525080803_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Practical_18.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rajkot",
                            Age = 22,
                            FirstName = "Bhautik",
                            LastName = "Ranpara",
                            Mobile = "9998887774"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Chicago",
                            Age = 35,
                            FirstName = "Ted",
                            LastName = "Mosby",
                            Mobile = "9995556623"
                        },
                        new
                        {
                            Id = 3,
                            Address = "LA",
                            Age = 26,
                            FirstName = "Barney",
                            LastName = "Stinson",
                            Mobile = "6655448811"
                        },
                        new
                        {
                            Id = 4,
                            Address = "NYC",
                            Age = 36,
                            FirstName = "Lily",
                            LastName = "Aldrin",
                            Mobile = "9988556633"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Texas",
                            Age = 30,
                            FirstName = "Robin",
                            LastName = "Scherbatsky",
                            Mobile = "4488556622"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
